---
title: "CanvasXpress Time Series Questions and Bugs"
format: 
    html:
        embed-resources: true
        smooth-scroll: true
include-in-header:
  text: 
    <link rel='stylesheet' href='https://www.canvasxpress.org/dist/canvasXpress.css' type='text/css'/>
    <script type='text/javascript' src='https://www.canvasxpress.org/dist/canvasXpress.min.js'></script>
---

## Working Example, Basic

Let us consider a basic time series chart that works:

```{ojs}
//| echo: true
//| output: false
new CanvasXpress(
    {
        "renderTo": "basic_example",
        "data": {
            "y" : {
                "smps" : ["date","Series A", "Series B"],
                "data" : [
                    [1674950400000, 30, 50],
                    [1675036800000, 80, 70],
                    [1675123200000, null, 40],
                    [1675209600000, null, 30],
                    [1675296000000, null, 20],
                    [1675468800000,  0, 20],
                    [1675555200000,  0, 50],
                    [1675641600000, 40, 70]
                ]
            }
        },
        "config": {
            "graphType": "Scatter2D",
            "scatterType": "line",
            "title": "basic_example",

            "xAxis": ["date"],
            "xAxisTime": true,
            "xAxisTitle": "Days",

            "yAxis": ["Series A", "Series B"],
            "yAxisTitle": "Values over Time",

            "timeFormat": "isoDate",

            "setMinX": 1674950400000,
            "setMaxX": 1675641600000,

            "dataPointSize": 75,
            "lineThickness": 2,
        }
    }
);
```

## Working Example, Dashed Line

We can format the lines, such as to indciate one line should be dashed:

```{ojs}
//| echo: true
//| output: false
new CanvasXpress(
    {
        "renderTo": "line_formatting_example_1",
        "data": {
            "y" : {
                "smps" : ["date","Series A", "Series B"],
                "data" : [
                    [1674864000000, 10, 20],
                    [1674950400000, 30, 50],
                    [1675036800000, 80, 70],
                    [1675123200000, 30, 40],
                    [1675209600000, 40, 30],
                    [1675296000000, 20, 20],
                    [1675468800000,  0, 20],
                    [1675555200000,  0, 50],
                    [1675641600000, 40, 70]
                ]
            },
            "x": {
                "series": ["-", "A", "B"],
                "seriesThickness": [0, 2, 4],
            }
        },
        "config": {
            "graphType": "Scatter2D",
            "scatterType": "line",
            "title": "Line thicknesses should be by sample/series",

            "xAxis": ["date"],
            "xAxisTime": true,
            "xAxisTitle": "Days",

            "yAxis": ["Series A", "Series B"],
            "yAxisTitle": "Scores",

            "timeFormat": "isoDate",

            "lineBy": "series",
            "linePatterns": ["dotted", "solid"],
            // "lineThickness": [2, 4],
            // "lineThickness": "seriesThickness",
            "lineThickness": 3,
            "dataPointSize": 20
        }
    }
);
```

```{=html}
<canvas id="line_formatting_example_1" width="800px"/>
```

This works, but the legend shows:

- kind
    - dashed
    - solid
- [default]
    - Series A
    - Series B

### Question 1

Is there a configuration that allows us to consolidate the legend so that only the default legend is displayed _with_ the line formatting applied in addition to the color?  We also tried `"linePatterns": ["solid", "dotted"]` (etc.) but that had no effect.

### Question 2

We would also like to format the lines in other ways, such as by changing the thickness.  We cannot find a method that works--is there a configuration for such?  We tried `"lineThicness": [5, 15]` (etc.) but that had no effect.

## Non-Working Example, Formatted Points

We also want to format plotted value points, but we cannot get that to work.  As an example, we tried: 

```{ojs}
//| echo: true
//| output: false
new CanvasXpress(
    {
        "renderTo": "example",
        "data": {
            "y" : {
                "smps" : ["date","A", "B"],
                "data" : [
                    [1674864000000, 10, 20],
                    [1674950400000, 30, 50],
                    [1675036800000, 80, 70],
                    [1675123200000, null, 40],
                    [1675209600000, null, 30],
                    [1675296000000, null, 20],
                    [1675468800000,  0, 20],
                    [1675555200000,  0, 50],
                    [1675641600000, 40, 70]
                ]
            },
        },
        "config": {
            "graphType": "Scatter2D",
            "scatterType": "Line",
            // "scatterType": "lineImage",
            "title": "Point shapes should be consistent by sample/series",

            "xAxis": ["date"],
            "xAxisTime": true,
            "xAxisTitle": "Days",

            "yAxis": ["A", "B"],
            "yAxisTitle": "Scores",

            "timeFormat": "isoDate",

            "dataPointSize": 20,
            // "shapeBy": "sample",
            // "shapes": ["star", "hexagon"]
        }
    }
);
```